--------------------------------------------------------------------
-- |
-- Module      : Text.PDF.Test
-- Description : Functions for testing PDF library routines.
-- Copyright   : (c) Dylan McNamee, 2009
-- License     : BSD3
--
-- Maintainer: Dylan McNamee <dylan@galois.com>
-- Stability : provisional
-- Portability: portable
--
-- Testing PDF parser and generator routines.
--------------------------------------------------------------------
module Text.PDF.Test where
